### ISSUE TITLE
App crashes when opening vue-devtools/vuex

### ISSUE THREAD

**Issue by econic** [unadlib/usm-vuex-demo#2]
The app crashes when you open the "vuex" tab of vue-devtools.

![image](https://user-images.githubusercontent.com/1814391/56212432-4a37ba00-605a-11e9-8384-9c4df9a459da.png)

As you can see, navigation and mutations work fine (i made three mutations) and then, when opening devtools _and switching to the vuex tab_, the app chrashes.

The erroring line is this:
![image](https://user-images.githubusercontent.com/1814391/56212690-cdf1a680-605a-11e9-8636-d38160514ad9.png)

Current master / current chrome / current vue devtools

**Comment by unadlib** [comment]
OK, I am checking.

**Comment by unadlib** [comment]
Bugs cannot be reproduced in my environment. Can you provide more detail information about the environment?
![image](https://user-images.githubusercontent.com/18650460/56213192-27bf9400-608e-11e9-810e-50150885ddb9.png)

**Comment by econic** [comment]
was somehow related to my vue devtools - reinstalled them, now it works fine
